apiVersion: vpc.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: hello-crossplane-alibabacloud
spec:
  forProvider:
    cidrBlock: 10.0.0.0/8
    description: test
    enableIpv6: true
    ipv6Isp: BGP
    vpcName: hello-crossplane-alibabacloud
