apiVersion: cdn.alibabacloud.crossplane.io/v1alpha1
kind: FcTrigger
metadata:
  annotations:
    meta.upbound.io/example-id: cdn/v1alpha1/fctrigger
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    eventMetaName: LogFileCreated
    eventMetaVersion: 1.0.0
    notes: example_value
    roleArn: acs:ram::${data.alicloud_account.default.id}:role/aliyuncdneventnotificationrole
    sourceArn: acs:cdn:*:${data.alicloud_account.default.id}:domain/example.com
    triggerArn: acs:fc:${data.alicloud_regions.default.regions.0.id}:${data.alicloud_account.default.id}:services/FCTestService/functions/printEvent/triggers/testtrigger
