apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: CustomLine
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/customline
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    customLineName: tf-example
    domainNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    ipSegmentList:
    - endIp: 192.0.2.125
      startIp: 192.0.2.123
