apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: Domain
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    domainName: starmove.com
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    tags:
      Created: TF
      For: example

---

apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: DomainGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/domain
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    domainGroupName: tf-example
