apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: GtmInstance
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/gtminstance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    alertConfig:
    - dingtalkNotice: true
      emailNotice: true
      noticeType: ADDR_ALERT
      smsNotice: true
    alertGroup:
    - ${alicloud_cms_alarm_contact_group.default.alarm_contact_group_name}
    cnameType: PUBLIC
    healthCheckTaskCount: 100
    instanceName: tf_example
    packageEdition: standard
    paymentType: Subscription
    period: 1
    publicCnameMode: SYSTEM_ASSIGN
    publicUserDomainName: ${var.domain_name}
    renewalStatus: ManualRenewal
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
    smsNotificationCount: 1000
    ttl: 60

---

apiVersion: cloudmonitorservice.alibabacloud.crossplane.io/v1alpha1
kind: AlarmContactGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/gtminstance
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    alarmContactGroupName: tf_example
