apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: AddressPool
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/addresspool
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    address:
    - address: 1.1.1.1
      attributeInfo: |2
            {
              "lineCodeRectifyType": "RECTIFIED",
              "lineCodes": ["os_namerica_us"]
            }
      lbaWeight: 1
      mode: SMART
      remark: address_remark
    addressPoolName: crossplane_example
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    lbaStrategy: RATIO
    type: IPV4

---

apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: GtmInstance
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/addresspool
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    alertConfig:
    - dingtalkNotice: true
      emailNotice: true
      noticeType: ADDR_ALERT
      smsNotice: true
    alertGroup:
    - crossplane_example
    cnameType: PUBLIC
    healthCheckTaskCount: 100
    instanceName: crossplane_example
    packageEdition: standard
    paymentType: Subscription
    period: 1
    publicCnameMode: SYSTEM_ASSIGN
    publicUserDomainName: alicloud-provider.com
    renewalStatus: ManualRenewal
#    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
    smsNotificationCount: 1000
    ttl: 60

---

apiVersion: cloudmonitorservice.alibabacloud.crossplane.io/v1alpha1
kind: AlarmContactGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/addresspool
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    alarmContactGroupName: crossplane_example
