apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: CustomLine
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/customline
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    customLineName: crossplane-example
    domainName: starmove.com
    ipSegmentList:
    - endIp: 192.0.2.125
      startIp: 192.0.2.123