apiVersion: alidns.alibabacloud.crossplane.io/v1alpha1
kind: DomainGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alidns/v1alpha1/domaingroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    domainGroupName: crossplane-example
