apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: NetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterface
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    region: cn-zhangjiakou
    description: Basic test
    networkInterfaceName: crossplane-example
    primaryIpAddress: 192.168.0.2
#    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.ids.0}
    securityGroupRefs:
    - name: eni
    tags:
      Created: TF
      For: Test
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eni

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterface
  labels:
    testing.upbound.io/example-name: eni
  name: eni
spec:
  forProvider:
    region: cn-zhangjiakou
    securityGroupName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eni

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterface
  labels:
    testing.upbound.io/example-name: eni
  name: eni
spec:
  forProvider:
    region: cn-zhangjiakou
    cidrBlock: 192.168.0.0/16
    vpcName: crossplane-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/networkinterface
  labels:
    testing.upbound.io/example-name: eni
  name: eni
spec:
  forProvider:
    region: cn-zhangjiakou
    cidrBlock: 192.168.0.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eni
    vswitchName: crossplane-example
    zoneId: cn-zhangjiakou-a
