apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: HealthCheckTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/healthchecktemplate
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    healthCheckTemplateName: crossplane-example
    region: cn-beijing
