apiVersion: polardb.alibabacloud.crossplane.io/v1alpha1
kind: BackupPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/backuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    backupRetentionPolicyOnClusterDeletion: NONE
    dbClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    preferredBackupPeriod:
    - Tuesday
    - Wednesday
    preferredBackupTime: 10:00Z-11:00Z
    region: cn-beijing

---

apiVersion: polardb.alibabacloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/backuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    dbNodeClass: ${data.alicloud_polardb_node_classes.default.classes.0.supported_engines.0.available_resources.0.db_node_class}
    dbType: MySQL
    dbVersion: "8.0"
    description: terraform-example
    payType: PostPaid
    region: cn-beijing
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/backuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: cn-beijing
    vpcName: terraform-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/backuppolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.16.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: terraform-example
    zoneId: ${data.alicloud_polardb_node_classes.default.classes[0].zone_id}
