apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: AccountPasswordPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/accountpasswordpolicy
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider: {}
