apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: policy
  name: policy
spec:
  forProvider:
    description: this is a policy test
    policyDocument: |2
        {
          "Statement": [
            {
              "Action": [
                "oss:ListObjects",
                "oss:GetObject"
              ],
              "Effect": "Allow",
              "Resource": [
                "acs:oss:*:*:mybucket",
                "acs:oss:*:*:mybucket/*"
              ]
            }
          ],
            "Version": "1"
        }
    policyName: tf-example-${random_integer.default.result}
