apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/role
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    description: this is a role test.
    document: "  {\n    \"Statement\": [\n      {\n        \"Action\": \"sts:AssumeRole\",\n
      \       \"Effect\": \"Allow\",\n        \"Principal\": {\n          \"Service\":
      [\n            \"apigateway.aliyuncs.com\", \n            \"ecs.aliyuncs.com\"\n
      \         ]\n        }\n      }\n    ],\n    \"Version\": \"1\"\n  }\n"
    name: terraform-example
