apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: UserGroupAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/usergroupattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    groupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    userNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/usergroupattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: terraform-example-${random_integer.default.result}

---

apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: ram/v1alpha1/usergroupattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    displayName: terraform-example-${random_integer.default.result}
    name: terraform-example-${random_integer.default.result}
