apiVersion: messageservice.alibabacloud.crossplane.io/v1alpha1
kind: Subscription
metadata:
  annotations:
    meta.upbound.io/example-id: messageservice/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    endpoint: http://example.com
    filterTag: crossplane-example
    notifyContentFormat: XML
    notifyStrategy: BACKOFF_RETRY
    pushType: http
    subscriptionName: crossplane-example
    topicNameSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: messageservice.alibabacloud.crossplane.io/v1alpha1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: messageservice/v1alpha1/subscription
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    enableLogging: true
    maxMessageSize: 16888
    topicName: crossplane-example
