apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpointZone
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    endpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone
    zoneId: cn-beijing-h

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    securityGroupRefs:
    - name: example-for-zone
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone
    vpcEndpointName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VPCEndpointService
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    autoAcceptConnection: false
    connectBandwidth: 103
    serviceDescription: crossplane-example

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpointServiceResource
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    resourceId: ${alicloud_slb_load_balancer.example.id}
    resourceType: slb
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    securityGroupName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    cidrBlock: 10.0.0.0/8
    vpcName: crossplane-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointzone
  labels:
    testing.upbound.io/example-name: example-for-zone
  name: example-for-zone
spec:
  forProvider:
    cidrBlock: 10.1.0.0/16
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-zone
    vswitchName: crossplane-example
    zoneId: cn-beijing-h
