apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpointConnection
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    bandwidth: 1024
    endpointIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    securityGroupRefs:
    - name: example-for-connection
    serviceId: ${alicloud_privatelink_vpc_endpoint_service.example.id}
    vpcEndpointName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VPCEndpointService
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    autoAcceptConnection: false
    connectBandwidth: 103
    serviceDescription: crossplane-example

---

apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpointServiceResource
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    resourceId: ${alicloud_slb_load_balancer.example.id}
    resourceType: slb
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    securityGroupName: crossplane-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    cidrBlock: 10.0.0.0/8
    vpcName: crossplane-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpointconnection
  labels:
    testing.upbound.io/example-name: example-for-connection
  name: example-for-connection
spec:
  forProvider:
    cidrBlock: 10.1.0.0/16
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-for-connection
    vswitchName: crossplane-example
    zoneId: cn-beijing-h
