apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/key
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: Hello KMS
    pendingWindowInDays: 7
    status: Enabled
