apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    forceDeleteWithoutRecovery: true
    secretDataSecretRef:
      key: secret
      name: sample-secret
      namespace: crossplane-system
    secretName: crossplane-example
    versionId: v1


---

apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: polardb/v1alpha1/account
  name: sample-secret
  namespace: crossplane-system
type: Opaque
stringData:
  secret: TestPass0!