apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: DedicatedHostCluster
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/dedicatedhostcluster
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dedicatedHostClusterName: example_value
    description: example_value
    tags:
      Create: TF
      For: DDH_Cluster_Test
    zoneId: ${data.alicloud_zones.example.zones.0.id}
