apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: DiskAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    diskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    category: cloud_efficiency
    deleteAutoSnapshot: "true"
    description: Test For Terraform
    diskName: ${var.name}
    enableAutoSnapshot: "true"
    encrypted: "true"
    region: cn-beijing
    size: "500"
    tags:
      Created: TF
      Environment: Acceptance-test
    zoneId: ${data.alicloud_zones.disk.zones.0.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    availabilityZone: ${data.alicloud_zones.default.zones.0.id}
    hostName: ${var.name}
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceName: ${var.name}
    instanceType: ${data.alicloud_instance_types.default.instance_types.0.id}
    region: cn-beijing
    securityGroupRefs:
    - name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: New security group
    name: tf-example
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/diskattachment
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 10.4.0.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    zoneId: ${data.alicloud_zones.default.zones.0.id}
