apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/image
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    architecture: x86_64
    description: terraform-example
    imageName: terraform-example-${random_integer.default.result}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    region: cn-beijing
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.ids.0}
    tags:
      FinanceDept: FinanceDeptJoshua

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/image
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    availabilityZone: ${data.alicloud_zones.default.zones.0.id}
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceName: terraform-example
    instanceType: ${data.alicloud_instance_types.default.ids[0]}
    internetMaxBandwidthOut: 10
    region: cn-beijing
    securityGroupRefs:
    - name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/image
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: terraform-example
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/image
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    region: cn-beijing
    vpcName: terraform-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/image
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: terraform-example
    zoneId: ${data.alicloud_zones.default.zones.0.id}
