apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: ImageImport
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/imageimport
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    architecture: x86_64
    description: ${var.name}
    diskDeviceMapping:
    - diskImageSize: 5
      ossBucket: ${alicloud_oss_bucket.default.id}
      ossObject: ${alicloud_oss_bucket_object.default.id}
    imageName: ${var.name}
    licenseType: Auto
    osType: linux
    platform: Ubuntu

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/imageimport
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucket: ${var.name}-${random_integer.default.result}

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/imageimport
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    content: |2
          # -*- coding: utf-8 -*-
          def handler(event, context):
          print "hello world"
          return 'hello world'
    key: fc/hello.zip
