apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: LaunchTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/launchtemplate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    dataDisks:
    - category: cloud
      deleteWithInstance: "true"
      description: description
      encrypted: "false"
      name: disk1
      performanceLevel: PL0
      size: "20"
    - category: cloud
      deleteWithInstance: "true"
      description: description2
      encrypted: "false"
      name: disk2
      performanceLevel: PL0
      size: "20"
    description: terraform-example
    hostName: terraform-example
    imageId: ${data.alicloud_images.default.images.0.id}
    instanceChargeType: PrePaid
    instanceName: terraform-example
    instanceType: ${data.alicloud_instance_types.default.instance_types.0.id}
    internetChargeType: PayByBandwidth
    internetMaxBandwidthIn: "5"
    internetMaxBandwidthOut: "5"
    ioOptimized: optimized
    keyPairNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    launchTemplateName: terraform-example
    networkInterfaces:
    - description: hello1
      name: eth0
      primaryIp: 10.0.0.2
      securityGroupId: ${alicloud_security_group.default.id}
      vswitchId: ${alicloud_vswitch.default.id}
    networkType: vpc
    ramRoleName: ram_role_name
    securityEnhancementStrategy: Active
    securityGroupRefs:
    - name: default
    spotPriceLimit: "5"
    spotStrategy: SpotWithPriceLimit
    systemDisk:
    - category: cloud_ssd
      deleteWithInstance: "false"
      description: Test For Terraform
      name: terraform-example
      size: "40"
    templateTags:
      Create: Terraform
      For: example
    userData: xxxxxxx
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    zoneId: ${data.alicloud_zones.default.zones.0.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/launchtemplate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    securityGroupName: terraform-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/launchtemplate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    vpcName: terraform-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/launchtemplate
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: terraform-example
    zoneId: ${data.alicloud_zones.default.zones.0.id}
