apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/securitygroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    securityGroupName: terraform-example
