apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SnapshotGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: terraform-example
    diskId:
    - ${alicloud_disk_attachment.default.disk_id}
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    instantAccess: true
    instantAccessRetentionDays: 1
    snapshotGroupName: terraform-example
    tags:
      Created: TF
      For: Acceptance

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    category: cloud_essd
    description: terraform-example
    diskName: terraform-example
    size: "30"
    zoneId: ${data.alicloud_zones.default.zones.0.id}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    availabilityZone: ${data.alicloud_zones.default.zones.0.id}
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceName: terraform-example
    instanceType: ${data.alicloud_instance_types.default.instance_types.0.id}
    internetMaxBandwidthOut: 10
    securityGroupRefs:
    - name: default
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    name: terraform-example
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    vpcName: terraform-example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshotgroup
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 172.17.3.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: terraform-example
    zoneId: ${data.alicloud_zones.default.zones.0.id}
