apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    category: standard
    diskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    retentionDays: 20

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Disk
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    category: cloud_essd
    diskName: ${var.name}
    size: 500
    zoneId: ${data.alicloud_instance_types.default.instance_types.0.availability_zones.0}

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: DiskAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    diskIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    availabilityZone: ${data.alicloud_instance_types.default.instance_types.0.availability_zones.0}
    dataDisks:
    - category: cloud_essd
      size: 20
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceChargeType: PostPaid
    instanceName: ${var.name}
    instanceType: ${data.alicloud_instance_types.default.instance_types.0.id}
    internetChargeType: PayByTraffic
    internetMaxBandwidthOut: "10"
    securityGroupSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    systemDiskCategory: cloud_essd
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    securityGroupName: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 192.168.0.0/16
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: ecs/v1alpha1/snapshot
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    cidrBlock: 192.168.192.0/24
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.default.zones.0.id}
