apiVersion: kms.alibabacloud.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    forceDeleteWithoutRecovery: true
    region: cn-beijing
    secretDataSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretName: ${var.name}
    versionId: v1
