apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    key: example_key
    source: ./main.tf

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucket: terraform-example-${random_integer.default.result}

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: default
