apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketWorm
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketworm
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: defaulthNMfIF
    region: cn-beijing
    retentionPeriodInDays: "1"
    status: InProgress

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketworm
  labels:
    testing.upbound.io/example-name: defaulthNMfIF
  name: defaulthnmfif
spec:
  forProvider:
    region: cn-beijing
    storageClass: Standard
