apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketStyle
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketstyle
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: CreateBucket
    category: document
    content: image/resize,p_75,w_75
    styleName: style-933

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketstyle
  labels:
    testing.upbound.io/example-name: CreateBucket
  name: createbucket
spec:
  forProvider:
    bucket: ${var.name}-${random_integer.default.result}
    storageClass: Standard
