apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: bucket-acl
  name: bucket-acl
spec:
  forProvider:
    bucket: example-value-${random_integer.default.result}
    region: cn-beijing

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: bucket-acl
  name: bucket-acl
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket-acl
    region: cn-beijing
