apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketWebsite
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketwebsite
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: defaultnVj9x3
    errorDocument:
    - httpStatus: "404"
      key: error.html
    indexDocument:
    - suffix: index.html
      supportSubDir: "true"
      type: "0"
    region: cn-beijing
    routingRules:
    - routingRule:
      - condition:
        - httpErrorCodeReturnedEquals: "404"
        luaConfig:
        - script: example.lua
        redirect:
        - hostName: www.alicdn-master.com
          httpRedirectCode: "305"
          protocol: https
          redirectType: AliCDN
        ruleNumber: "1"

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketwebsite
  labels:
    testing.upbound.io/example-name: defaultnVj9x3
  name: defaultnvj9x3
spec:
  forProvider:
    bucket: ${var.name}-${random_uuid.default.result}
    region: cn-beijing
    storageClass: Standard
