---
apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: AccountPasswordPolicy
metadata:
  annotations:
    meta.crossplane.io/example-id: ram-v1alpha1-test-accountpasswordpolicy-1
  labels:
    testing.crossplane.io/example-name: default
  name: default
spec:
  # Setting defaults when no parameters are specified
  forProvider:
    minimumPasswordLength: 8
    requireLowerCaseCharacters: false
    requireUpperCaseCharaters: false
    requireNumbers: false
    requireSymbols: false
    hardExpiry: false
    maxPasswordAge: 0
    passwordReusePrevention: 0
    maxLoginAttempts: 32
