---
apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.crossplane.io/example-id: ram-v1alpha1-test-rolepolicyattachment-1
  labels:
    testing.crossplane.io/example-name: test-rolepolicyattachment-1
  name: test-rolepolicyattachment-1
spec:
  forProvider:
    policyName: test-policy-for-rolepolicyattachment-1
    policyType: Custom
    roleName: test-role-for-rolepolicyattachment-1
---
apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.crossplane.io/example-id: ram-v1alpha1-test-policy-for-rolepolicyattachment-1
  labels:
    testing.crossplane.io/example-name: test-policy-for-rolepolicyattachment-1
  name: test-policy-for-rolepolicyattachment-1
spec:
  forProvider:
    description: This is a test policy for rolepolicyattachment created by provider-upjet-alibabacloud
    policyDocument: |
        {
          "Statement": [
            {
              "Action": [
                "oss:ListObjects",
                "oss:GetObject"
              ],
              "Effect": "Allow",
              "Resource": [
                "acs:oss:*:*:mybucket",
                "acs:oss:*:*:mybucket/*"
              ]
            }
          ],
            "Version": "1"
        }
    policyName: test-policy-for-rolepolicyattachment-1
---
apiVersion: ram.alibabacloud.crossplane.io/v1alpha1
kind: Role
metadata:
  annotations:
    meta.crossplane.io/example-id: ram-v1alpha1-role-for-rolepolicyattachment-1
  labels:
    testing.crossplane.io/example-name: test-role-for-rolepolicyattachment-1
  name: test-role-for-rolepolicyattachment-1
spec:
  forProvider:
    description: This is a test role for rolepolicyattachment created by provider-upjet-alibabacloud
    document: "    {\n      \"Statement\": [\n        {\n          \"Action\": \"sts:AssumeRole\",\n
      \         \"Effect\": \"Allow\",\n          \"Principal\": {\n            \"Service\":
      [\n              \"apigateway.aliyuncs.com\", \n              \"ecs.aliyuncs.com\"\n
      \           ]\n          }\n        }\n      ],\n      \"Version\": \"1\"\n
      \   }\n"
    name: test-role-for-rolepolicyattachment-1
