apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    bucket: example-value-bucket-202504081600

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: bucket
  name: bucket
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucket
