apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketObject
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketobject
    key: example_key
    content: "the content that you want to upload."

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: bucketobject
  name: bucketobject
spec:
  forProvider:
    bucket: crossplane-example-bucketobject-202504081600

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketobject
  labels:
    testing.upbound.io/example-name: bucketobject
  name: bucketobject
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketobject
