apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketHTTPSConfig
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/buckethttpsconfig
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: buckethttpsconfig
    enable: true
    tlsVersions:
    - TLSv1.2

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/buckethttpsconfig
  labels:
    testing.upbound.io/example-name: buckethttpsconfig
  name: buckethttpsconfig
spec:
  forProvider:
    bucket: crossplane-example-buckethttpsconfig-202504081600
    storageClass: Standard
