apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketReplication
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketreplication
  labels:
    testing.upbound.io/example-name: cross-region-replication
  name: cross-region-replication
spec:
  forProvider:
    action: PUT,DELETE
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketreplication-src
    destination:
      - bucketSelector:
          matchLabels:
            testing.upbound.io/example-name: bucketreplication-dest
        locationSelector:
          matchLabels:
            testing.upbound.io/example-name: bucketreplication-dest
#    encryptionConfiguration:
#      - replicaKmsKeyId: ${alicloud_kms_key.key.id}
    historicalObjectReplication: enabled
    prefixSet:
      - prefixes:
          - prefix1/
          - prefix2/
    sourceSelectionCriteria:
      - sseKmsEncryptedObjects:
          - status: Enabled
#    syncRole: ${alicloud_ram_role.role.name}

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketreplication
  labels:
    testing.upbound.io/example-name: bucketreplication-dest
  name: bucketreplication-dest
spec:
  forProvider:
    bucket: example-dest-bucketreplication-202504081600

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketreplication
  labels:
    testing.upbound.io/example-name: bucketreplication-src
  name: bucketreplication-src
spec:
  forProvider:
    bucket: example-src-bucketreplication-202504081600
