apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketAccessMonitor
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketaccessmonitor
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketaccessmonitor
    status: Enabled

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketaccessmonitor
  labels:
    testing.upbound.io/example-name: bucketaccessmonitor
  name: bucketaccessmonitor
spec:
  forProvider:
    bucket: crossplane-example-bucketaccessmonitor-202504081600
    storageClass: Standard
