apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketLogging
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketlogging
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketlogging
    targetBucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketlogging
    targetPrefix: log/

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketlogging
  labels:
    testing.upbound.io/example-name: bucketlogging
  name: bucketlogging
spec:
  forProvider:
    bucket: crossplane-example-bucketlogging-202504081600
    storageClass: Standard
