apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: BucketACL
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketacl
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    acl: private
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: bucketacl

---

apiVersion: oss.alibabacloud.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: oss/v1alpha1/bucketacl
  labels:
    testing.upbound.io/example-name: bucketacl
  name: bucketacl
spec:
  forProvider:
    bucket: crossplane-example-bucketacl-202504081600
    storageClass: Standard
