apiVersion: privatelink.alibabacloud.crossplane.io/v1alpha1
kind: VpcEndpoint
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpoint
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    dryRun: "false"
    endpointDescription: ${var.name}
    endpointType: Interface
    policyDocument: '${jsonencode({ "Version" : "1", "Statement" : [{ "Effect" : "Allow",
      "Action" : ["*"], "Resource" : ["*"], "Principal" : "*" }] })}'
    protectedEnabled: "false"
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.ids.0}
    securityGroupRefs:
    - name: default1FTFrP
    serviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    serviceName: com.aliyuncs.privatelink.ap-southeast-5.oss
    vpcEndpointName: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: defaultbFzA4a
    zonePrivateIpAddressCount: "1"

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpoint
  labels:
    testing.upbound.io/example-name: default1FTFrP
  name: default1ftfrp
spec:
  forProvider:
    name: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: defaultbFzA4a

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpoint
  labels:
    testing.upbound.io/example-name: defaultjljY5S
  name: defaultjljy5s
spec:
  forProvider:
    name: ${var.name}
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: defaultbFzA4a

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: privatelink/v1alpha1/vpcendpoint
  labels:
    testing.upbound.io/example-name: defaultbFzA4a
  name: defaultbfza4a
spec:
  forProvider:
    cidrBlock: 172.16.0.0/12
    description: example-terraform
    vpcName: ${var.name}
