apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: Acl
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/acl
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    aclName: tf_example
    region: cn-beijing
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.default.groups.0.id}
