apiVersion: alb.alibabacloud.crossplane.io/v1alpha1
kind: ServerGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    healthCheckConfig:
    - healthCheckCodes:
      - http_2xx
      - http_3xx
      - http_4xx
      healthCheckConnectPort: "46325"
      healthCheckEnabled: true
      healthCheckHost: tf-example.com
      healthCheckHttpVersion: HTTP1.1
      healthCheckInterval: "2"
      healthCheckMethod: HEAD
      healthCheckPath: /tf-example
      healthCheckProtocol: HTTP
      healthCheckTimeout: 5
      healthyThreshold: 3
      unhealthyThreshold: 3
    protocol: HTTP
    region: cn-beijing
    resourceGroupId: ${data.alicloud_resource_manager_resource_groups.example.groups.0.id}
    serverGroupName: ${var.name}
    servers:
    - description: ${var.name}
      port: 80
      serverIdSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      serverIpSelector:
        matchLabels:
          testing.upbound.io/example-name: example
      serverType: Ecs
      weight: 10
    stickySessionConfig:
    - cookie: tf-example
      stickySessionEnabled: true
      stickySessionType: Server
    tags:
      Created: TF
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    availabilityZone: ${data.alicloud_zones.example.zones.0.id}
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud_images
    instanceName: ${var.name}
    instanceType: ${data.alicloud_instance_types.example.instance_types.0.id}
    region: cn-beijing
    securityGroupRefs:
    - name: example
    vswitchIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: ecs.alibabacloud.crossplane.io/v1alpha1
kind: SecurityGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: ${var.name}
    name: ${var.name}
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcName: ${var.name}

---

apiVersion: vpc.alibabacloud.crossplane.io/v1alpha1
kind: Vswitch
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/servergroup
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cidrBlock: 10.4.0.0/16
    region: cn-beijing
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vswitchName: ${var.name}
    zoneId: ${data.alicloud_zones.example.zones.0.id}
